apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    app.kubernetes.io/name: inari-operator
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: controller-manager
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: ghcr.io/7k-inari/inari-operator:latest
          imagePullPolicy: IfNotPresent
          args:
            - --leader-elect
          env:
            - name: KEYCLOAK_URL
              valueFrom:
                secretKeyRef:
                  name: inari-operator-keycloak
                  key: url
                  optional: true
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: inari-operator-keycloak
                  key: client-secret
                  optional: true
          ports:
            - containerPort: 8080
              name: metrics
            - containerPort: 8081
              name: health
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
