---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  - resourcequotas
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - impersonate
- apiGroups:
  - argoproj.io
  resources:
  - appprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - clusterissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - externaldns.k8s.io
  resources:
  - dnsendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.inari.io
  resources:
  - argoprojects
  - certissuers
  - dnsrecords
  - dnszones
  - keycloakclients
  - keycloakrealms
  - tenantnamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.inari.io
  resources:
  - argoprojects/finalizers
  - certissuers/finalizers
  - dnsrecords/finalizers
  - dnszones/finalizers
  - keycloakclients/finalizers
  - keycloakrealms/finalizers
  - tenantnamespaces/finalizers
  verbs:
  - update
- apiGroups:
  - platform.inari.io
  resources:
  - argoprojects/status
  - certissuers/status
  - dnsrecords/status
  - dnszones/status
  - keycloakclients/status
  - keycloakrealms/status
  - tenantnamespaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
